######################################################################
# Automatically generated by qmake (2.01a) Thu May 12 14:30:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += exit.h
SOURCES += exit.cpp line_exit.cpp
